
#ifndef TMR2_CONFIG_H_
#define TMR2_CONFIG_H_

#define TMR2_PRELOAD_VALUE 82
#define TMR2_OVER_FLOW_COUNTER 2930
#define TMR2_CTC_COUNTER 5000
#define TMR2_MODE TMR2_CTC_MODE
#endif /* TMR0_CONFIG_H_ */
